-- MOTS ShipIt -- Feature 5: carrier outreach (C4)
-- Applied to Supabase as migration create_carrier_interactions.
--   transportation_shipment.carrier_interactions: every outreach message, logged verbatim
--   sourcing_policies.outreach_disclosure_text: fixed first line of every message (never AI-written)

begin;

alter table operational_excellence_governance.sourcing_policies
  add column if not exists outreach_disclosure_text text not null
  default 'This is an automated message from MOTS ShipIt. Reply STOP to opt out.';

comment on column operational_excellence_governance.sourcing_policies.outreach_disclosure_text is
  'Fixed AI-disclosure line that opens every outreach message for this customer''s loads. Policy-controlled; never generated by the model.';

create table if not exists transportation_shipment.carrier_interactions (
  id uuid primary key default gen_random_uuid(),
  load_id uuid not null references transportation_shipment.loads (id) on delete cascade,
  load_version integer not null,
  carrier_id uuid not null references data_foundation.carriers (id) on delete cascade,
  carrier_contact_id uuid references data_foundation.carrier_contacts (id) on delete set null,
  batch_id uuid not null,
  direction text not null default 'outbound' check (direction in ('outbound', 'inbound')),
  channel text not null check (channel in ('email', 'sms', 'voice')),
  -- test: only the test recipient or a simulation; live: the carrier's real contact
  outreach_mode text not null check (outreach_mode in ('test', 'live')),
  status text not null check (status in ('simulated', 'sent', 'failed', 'skipped')),
  recipient text,
  disclosure_text text not null,
  message_text text not null,
  channel_reference text,
  skip_reason text,
  error_message text,
  attempts integer not null default 1,
  sent_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists carrier_interactions_load_idx
  on transportation_shipment.carrier_interactions (load_id, load_version, created_at desc);
create index if not exists carrier_interactions_contact_recent_idx
  on transportation_shipment.carrier_interactions (carrier_contact_id, created_at desc);

comment on table transportation_shipment.carrier_interactions is
  'Every message to or from a carrier about a load, logged verbatim with its AI disclosure line.';

alter table transportation_shipment.carrier_interactions enable row level security;

drop policy if exists "Signed-in users can read carrier interactions" on transportation_shipment.carrier_interactions;
create policy "Signed-in users can read carrier interactions" on transportation_shipment.carrier_interactions
  for select to authenticated using (true);

grant select on transportation_shipment.carrier_interactions to authenticated;
grant all on transportation_shipment.carrier_interactions to service_role;

commit;
