-- MOTS ShipIt -- Transportation and Shipment domain: routing guide
-- GENERATED by scripts/generate-routing-guide-sql.mjs from data/Routing_Guide.json -- do not edit by hand.
-- 52 entries. Safe to re-run: creation is idempotent, and the seed inserts new
-- entries and updates existing ones, matched on (geography, origin_hub, zipcode, carrier, mode, weight_break).

-- Runs as one transaction: if any step fails, nothing changes and existing routing guide records stay.
begin;

-- Geographies (Data Foundation): the code list routing_guide.geography must use.
create schema if not exists data_foundation;

create table if not exists data_foundation.geographies (
  code text primary key check (code ~ '^[A-Z]{2,6}$'),
  name text not null unique,
  created_at timestamptz not null default now()
);

comment on table data_foundation.geographies is
  'Geographies / marketplaces the organization operates in. code is the short code used on other tables (e.g. NA); name is the full name.';

alter table data_foundation.geographies enable row level security;

drop policy if exists "Signed-in users can read geographies" on data_foundation.geographies;
create policy "Signed-in users can read geographies"
  on data_foundation.geographies
  for select to authenticated
  using (true);

grant usage on schema data_foundation to authenticated, service_role;
grant select on data_foundation.geographies to authenticated;
grant all on data_foundation.geographies to service_role;

insert into data_foundation.geographies (code, name) values
  ('NA', 'North America'),
  ('EMEA', 'Europe'),
  ('APLA', 'Pacific Asia')
on conflict (code) do update set name = excluded.name;

-- Routing guide (Transportation and Shipment)
create schema if not exists transportation_shipment;

create table if not exists transportation_shipment.routing_guide (
  id uuid primary key default gen_random_uuid(),
  geography text not null references data_foundation.geographies (code),
  origin_hub text not null,
  state text not null,
  state_code text not null check (char_length(state_code) = 2),
  gateway_city text not null,
  street_address text not null,
  zipcode text not null check (zipcode ~ '^[0-9]{5}$'),
  corridor text not null,
  distance_miles integer not null check (distance_miles > 0),
  transit_days integer not null check (transit_days >= 0),
  mode text not null check (mode in ('FTL', 'LTL', 'Intermodal')),
  transport text not null check (transport in ('Road', 'Rail')),
  carrier text not null,
  freight_cost_dollars numeric(10, 2) not null check (freight_cost_dollars >= 0),
  weight_break text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint routing_guide_entry_unique
    unique nulls not distinct (geography, origin_hub, zipcode, carrier, mode, weight_break)
);

-- Upgrade path for a routing_guide created before the geography column existed.
alter table transportation_shipment.routing_guide
  add column if not exists geography text references data_foundation.geographies (code);
update transportation_shipment.routing_guide set geography = 'NA' where geography is null;
alter table transportation_shipment.routing_guide alter column geography set not null;
alter table transportation_shipment.routing_guide drop constraint if exists routing_guide_entry_unique;
alter table transportation_shipment.routing_guide add constraint routing_guide_entry_unique
  unique nulls not distinct (geography, origin_hub, zipcode, carrier, mode, weight_break);
create index if not exists routing_guide_geography_idx on transportation_shipment.routing_guide (geography);

comment on table transportation_shipment.routing_guide is
  'Routing guide: for each geography and origin hub, the ship-to destinations, the carriers enabled for each, and weight breaks. freight_cost_dollars is kept here for this phase in place of a separate rate table.';
comment on column transportation_shipment.routing_guide.weight_break is
  'Weight band this entry applies to (e.g. <= 100 lbs). Null means the entry applies to all weights.';

create index if not exists routing_guide_zipcode_idx on transportation_shipment.routing_guide (zipcode);
create index if not exists routing_guide_state_code_idx on transportation_shipment.routing_guide (state_code);

alter table transportation_shipment.routing_guide enable row level security;

drop policy if exists "Signed-in users can read the routing guide" on transportation_shipment.routing_guide;
create policy "Signed-in users can read the routing guide"
  on transportation_shipment.routing_guide
  for select to authenticated
  using (true);

grant usage on schema transportation_shipment to authenticated, service_role;
grant select on transportation_shipment.routing_guide to authenticated;
grant all on transportation_shipment.routing_guide to service_role;

-- Seed from data/Routing_Guide.json
insert into transportation_shipment.routing_guide
  (geography, origin_hub, state, state_code, gateway_city, street_address, zipcode, corridor, distance_miles, transit_days, mode, transport, carrier, freight_cost_dollars, weight_break)
values
  ('NA', 'Memphis, TN', 'Alabama', 'AL', 'Birmingham', '2201 1st Ave N', '35203', 'I-22 E', 240, 1, 'FTL', 'Road', 'Trax', 12.5, null),
  ('NA', 'Memphis, TN', 'Alaska', 'AK', 'Anchorage', '632 W 6th Ave', '99501', 'Interstate Highway / AK Route', 3400, 5, 'Intermodal', 'Road', 'FedEx', 5, null),
  ('NA', 'Memphis, TN', 'Arizona', 'AZ', 'Phoenix', '200 W Washington St', '85003', 'I-40 W to I-17 S', 1450, 3, 'Intermodal', 'Rail', 'BNSF', 3.2, null),
  ('NA', 'Memphis, TN', 'Arkansas', 'AR', 'Little Rock', '500 W Markham St', '72201', 'I-40 W', 135, 1, 'FTL', 'Road', 'Trax', 4.2, null),
  ('NA', 'Memphis, TN', 'California', 'CA', 'Los Angeles', '200 N Spring St', '90012', 'I-40 W Corridor', 1800, 4, 'LTL', 'Road', 'FedEx', 2.5, '<= 100 lbs'),
  ('NA', 'Memphis, TN', 'California', 'CA', 'Los Angeles', '200 N Spring St', '90012', 'BNSF Transcon Rail', 1800, 3, 'Intermodal', 'Rail', 'BNSF', 125, '> 100 lbs'),
  ('NA', 'Memphis, TN', 'Colorado', 'CO', 'Denver', '1437 Bannock St', '80202', 'I-40 W to US-287 N', 1050, 3, 'Intermodal', 'Rail', 'Union Pacific', 13.5, null),
  ('NA', 'Memphis, TN', 'Connecticut', 'CT', 'Hartford', '550 Main St', '06103', 'I-40 E to I-81 N / I-84 E', 1120, 3, 'LTL', 'Road', 'UPS', 12, null),
  ('NA', 'Memphis, TN', 'Delaware', 'DE', 'Wilmington', '800 N French St', '19801', 'I-40 E to I-81 N / I-95 N', 920, 2, 'LTL', 'Road', 'UPS', 5.8, null),
  ('NA', 'Memphis, TN', 'Florida', 'FL', 'Jacksonville', '117 W Duval St', '32202', 'I-22 E to I-10 E', 620, 2, 'LTL', 'Road', 'UPS', 8, null),
  ('NA', 'Memphis, TN', 'Georgia', 'GA', 'Atlanta', '55 Trinity Ave SW', '30303', 'I-22 E to I-20 E', 390, 1, 'Intermodal', 'Rail', 'Norfolk Southern', 1.5, null),
  ('NA', 'Memphis, TN', 'Hawaii', 'HI', 'Honolulu', '530 S King St', '96813', 'Overland Intermodal Shorthaul', 4200, 5, 'Intermodal', 'Road', 'FedEx', 3.8, null),
  ('NA', 'Memphis, TN', 'Idaho', 'ID', 'Boise', '150 N 8th St', '83702', 'I-40 W to I-84 W', 1820, 4, 'LTL', 'Road', 'Trax', 15.6, null),
  ('NA', 'Memphis, TN', 'Illinois', 'IL', 'Chicago', '121 N LaSalle St', '60602', 'I-55 N / Rail Spine', 530, 2, 'Intermodal', 'Rail', 'CSX', 2.8, null),
  ('NA', 'Memphis, TN', 'Indiana', 'IN', 'Indianapolis', '200 E Washington St', '46204', 'I-40 E to I-65 N', 465, 2, 'LTL', 'Road', 'UPS', 15, null),
  ('NA', 'Memphis, TN', 'Iowa', 'IA', 'Des Moines', '400 Robert D Ray Dr', '50309', 'I-55 N to I-80 W', 600, 2, 'LTL', 'Road', 'Trax', 9.6, null),
  ('NA', 'Memphis, TN', 'Kansas', 'KS', 'Wichita', '455 N Main St', '67202', 'I-40 W to US-400 W', 450, 2, 'LTL', 'Road', 'Trax', 5.3, null),
  ('NA', 'Memphis, TN', 'Kentucky', 'KY', 'Louisville', '601 W Jefferson St', '40202', 'I-40 E to I-65 N', 380, 1, 'LTL', 'Road', 'UPS', 14.8, null),
  ('NA', 'Memphis, TN', 'Louisiana', 'LA', 'New Orleans', '1300 Perdido St', '70112', 'I-55 S', 395, 1, 'FTL', 'Road', 'Trax', 6.4, null),
  ('NA', 'Memphis, TN', 'Maine', 'ME', 'Portland', '389 Congress St', '04101', 'I-40 E to I-81 N / I-95 N', 1320, 3, 'LTL', 'Road', 'Trax', 14.2, null),
  ('NA', 'Memphis, TN', 'Maryland', 'MD', 'Baltimore', '100 Holliday St', '21202', 'I-40 E to I-81 N / I-70 E', 870, 2, 'Intermodal', 'Rail', 'Norfolk Southern', 2.4, null),
  ('NA', 'Memphis, TN', 'Massachusetts', 'MA', 'Boston', '1 City Hall Sq', '02201', 'I-40 E to I-81 N / I-90 E', 1210, 3, 'LTL', 'Road', 'FedEx', 0.9, null),
  ('NA', 'Memphis, TN', 'Michigan', 'MI', 'Detroit', '2 Woodward Ave', '48226', 'I-55 N to I-94 E', 750, 2, 'Intermodal', 'Rail', 'Union Pacific', 17.5, null),
  ('NA', 'Memphis, TN', 'Minnesota', 'MN', 'Minneapolis', '350 S 5th St', '55415', 'I-55 N to I-35 N', 810, 2, 'Intermodal', 'Rail', 'BNSF', 1.2, null),
  ('NA', 'Memphis, TN', 'Mississippi', 'MS', 'Jackson', '219 S President St', '39201', 'I-55 S', 210, 1, 'FTL', 'Road', 'Trax', 2.1, null),
  ('NA', 'Memphis, TN', 'Missouri', 'MO', 'St. Louis', '1200 Market St', '63103', 'I-55 N', 285, 1, 'FTL', 'Road', 'Trax', 10.4, null),
  ('NA', 'Memphis, TN', 'Montana', 'MT', 'Billings', '210 N 27th St', '59101', 'I-55 N to I-90 W', 1420, 4, 'LTL', 'Road', 'Trax', 17.1, null),
  ('NA', 'Memphis, TN', 'Nebraska', 'NE', 'Omaha', '1819 Farnam St', '68183', 'I-55 N to I-80 W', 630, 2, 'LTL', 'Road', 'UPS', 6.8, null),
  ('NA', 'Memphis, TN', 'Nevada', 'NV', 'Las Vegas', '495 S Main St', '89101', 'I-40 W to US-93 N', 1600, 4, 'Intermodal', 'Rail', 'Union Pacific', 6.2, null),
  ('NA', 'Memphis, TN', 'New Hampshire', 'NH', 'Manchester', '1 City Hall Plaza', '03101', 'I-40 E to I-81 N / I-93 N', 1260, 3, 'LTL', 'Road', 'Trax', 9.1, null),
  ('NA', 'Memphis, TN', 'New Jersey', 'NJ', 'Newark', '920 Broad St', '07102', 'I-40 E to I-81 N / I-78 E', 1010, 3, 'LTL', 'Road', 'FedEx', 4, '<= 100 lbs'),
  ('NA', 'Memphis, TN', 'New Jersey', 'NJ', 'Newark', '920 Broad St', '07102', 'CSX Intermodal Rail', 1010, 3, 'Intermodal', 'Rail', 'CSX', 150, '> 100 lbs'),
  ('NA', 'Memphis, TN', 'New Mexico', 'NM', 'Albuquerque', '1 Civic Plaza NW', '87102', 'I-40 W', 1020, 2, 'Intermodal', 'Rail', 'BNSF', 11, null),
  ('NA', 'Memphis, TN', 'New York', 'NY', 'New York City', '1 Centre St', '10007', 'I-40 E to I-81 N', 1050, 3, 'Intermodal', 'Rail', 'CSX', 1.1, null),
  ('NA', 'Memphis, TN', 'North Carolina', 'NC', 'Charlotte', '600 E 4th St', '28202', 'I-40 E to I-77 S', 610, 2, 'LTL', 'Road', 'FedEx', 0.8, null),
  ('NA', 'Memphis, TN', 'North Dakota', 'ND', 'Fargo', '225 4th St N', '58102', 'I-55 N to I-29 N', 1050, 3, 'LTL', 'Road', 'Trax', 13.1, null),
  ('NA', 'Memphis, TN', 'Ohio', 'OH', 'Columbus', '90 W Broad St', '43215', 'I-40 E to I-71 N', 580, 2, 'Intermodal', 'Rail', 'CSX', 18, null),
  ('NA', 'Memphis, TN', 'Oklahoma', 'OK', 'Oklahoma City', '200 N Walker Ave', '73102', 'I-40 W', 465, 1, 'FTL', 'Road', 'Trax', 7.4, null),
  ('NA', 'Memphis, TN', 'Oregon', 'OR', 'Portland', '1221 SW 4th Ave', '97204', 'I-40 W to I-84 W', 2150, 4, 'Intermodal', 'Rail', 'BNSF', 3, null),
  ('NA', 'Memphis, TN', 'Pennsylvania', 'PA', 'Philadelphia', '1401 John F Kennedy Blvd', '19102', 'I-40 E to I-81 N', 930, 2, 'Intermodal', 'Rail', 'Norfolk Southern', 16.8, null),
  ('NA', 'Memphis, TN', 'Rhode Island', 'RI', 'Providence', '25 Dorrance St', '02903', 'I-40 E to I-81 N / I-95 N', 1200, 3, 'LTL', 'Road', 'UPS', 8.3, null),
  ('NA', 'Memphis, TN', 'South Carolina', 'SC', 'Charleston', '80 Broad St', '29401', 'I-40 E to I-26 E', 680, 2, 'LTL', 'Road', 'UPS', 11.3, null),
  ('NA', 'Memphis, TN', 'South Dakota', 'SD', 'Sioux Falls', '224 W 9th St', '57104', 'I-55 N to I-29 N', 780, 2, 'LTL', 'Road', 'Trax', 8.7, null),
  ('NA', 'Memphis, TN', 'Tennessee', 'TN', 'Nashville', '1 Public Sq', '37201', 'I-40 E', 210, 1, 'FTL', 'Road', 'FedEx', 3.5, null),
  ('NA', 'Memphis, TN', 'Texas', 'TX', 'Dallas', '1500 Marilla St', '75201', 'I-30 W (via Little Rock)', 450, 1, 'FTL', 'Road', 'FedEx', 1.8, null),
  ('NA', 'Memphis, TN', 'Utah', 'UT', 'Salt Lake City', '451 S State St', '84111', 'I-40 W to I-80 W', 1480, 4, 'Intermodal', 'Rail', 'Union Pacific', 11.8, null),
  ('NA', 'Memphis, TN', 'Vermont', 'VT', 'Burlington', '149 Church St', '05401', 'I-40 E to I-81 N / I-87 N', 1220, 3, 'LTL', 'Road', 'Trax', 10.9, null),
  ('NA', 'Memphis, TN', 'Virginia', 'VA', 'Richmond', '900 E Broad St', '23219', 'I-40 E to I-81 N', 760, 2, 'LTL', 'Road', 'UPS', 16.2, null),
  ('NA', 'Memphis, TN', 'Washington', 'WA', 'Seattle', '600 4th Ave', '98104', 'I-55 N to I-90 W', 2300, 4, 'Intermodal', 'Rail', 'BNSF', 1.6, null),
  ('NA', 'Memphis, TN', 'West Virginia', 'WV', 'Charleston', '501 Virginia St E', '25301', 'I-40 E to I-77 N', 570, 2, 'LTL', 'Road', 'Trax', 7.9, null),
  ('NA', 'Memphis, TN', 'Wisconsin', 'WI', 'Milwaukee', '200 E Wells St', '53202', 'I-55 N to I-94 E', 620, 2, 'LTL', 'Road', 'FedEx', 4.9, null),
  ('NA', 'Memphis, TN', 'Wyoming', 'WY', 'Cheyenne', '2101 O''Neil Ave', '82001', 'I-40 W to I-25 N', 1150, 3, 'LTL', 'Road', 'Trax', 8.9, null)
on conflict on constraint routing_guide_entry_unique do update set
  state = excluded.state,
  state_code = excluded.state_code,
  gateway_city = excluded.gateway_city,
  street_address = excluded.street_address,
  corridor = excluded.corridor,
  distance_miles = excluded.distance_miles,
  transit_days = excluded.transit_days,
  transport = excluded.transport,
  freight_cost_dollars = excluded.freight_cost_dollars,
  updated_at = now();

-- Safeguard: the knowledge base must hold at least every entry from the JSON for each geography in it.
do $$
declare
  expected record;
  actual integer;
begin
  for expected in
    select * from (values
      ('NA', 52)
    ) as e (geography, entries)
  loop
    select count(*) into actual
      from transportation_shipment.routing_guide
      where geography = expected.geography;
    if actual < expected.entries then
      raise exception 'Routing guide for % has % entries, expected at least % -- rolling back', expected.geography, actual, expected.entries;
    end if;
  end loop;
end $$;

commit;
